# Blongo is MIT. Zed's editor/terminal/markdown/ui crates are GPL-3.0 and must
# never enter the dependency graph; only permissive licenses are allowed.
[licenses]
allow = [
    "MIT", "MIT-0", "Apache-2.0", "Apache-2.0 WITH LLVM-exception", "BSD-2-Clause",
    "BSD-3-Clause", "ISC", "Zlib", "Unicode-3.0", "Unicode-DFS-2016", "CC0-1.0",
    "BSL-1.0", "MPL-2.0", "OFL-1.1", "Ubuntu-font-1.0", "bzip2-1.0.6", "CDLA-Permissive-2.0",
]
confidence-threshold = 0.8

[licenses.private]
ignore = true
