[package]
name = "blongo"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "blongo"
path = "src/main.rs"

[dependencies]
blongo-protocol.workspace = true
blongo-core.workspace = true
tokio.workspace = true
anyhow.workspace = true
unicode-segmentation.workspace = true
gpui.workspace = true
gpui_platform = { workspace = true, features = ["x11", "wayland", "font-kit"] }
mimalloc.workspace = true
