[package]
name = "blongo-server"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "blongo-serve"
path = "src/main.rs"

[dependencies]
blongo-protocol.workspace = true
blongo-core.workspace = true
blongo-client.workspace = true
tokio = { workspace = true, features = ["net", "io-std", "signal"] }
tokio-tungstenite.workspace = true
ed25519-dalek.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
portable-pty.workspace = true
libc.workspace = true
mimalloc.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["net", "io-std", "signal", "rt-multi-thread"] }
socket2 = "0.6"
